title: Mig Reyes
author: Mig Reyes
subtitle: "Designer, Basecamp"
description: Mig is a designer at Basecamp focused on making good things for good people.

github: http://github.com/migreyes
twitter: http://twitter.com/migreyes
dribbble: http://dribbble.com/migreyes
instagram: http://instagram.com/migreyes

source: ./_source
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:categories/:title
markdown: rdiscount
pygments: true